const HTTP_CREATED = 201;
const HTTP_BAD_REQUEST = 400;
const HTTP_UNAUTHORIZED = 401;

const HTTP_SERVER_ERROR = 500;

exports.HTTP_CREATED = HTTP_CREATED;
exports.HTTP_BAD_REQUEST = HTTP_BAD_REQUEST;
exports.HTTP_UNAUTHORIZED = HTTP_UNAUTHORIZED;
exports.HTTP_SERVER_ERROR = HTTP_SERVER_ERROR;
